/**
 * 
 */
export const medications = [
    { value: '1', label: 'ΦΑΡΜ. ΑΓΩΓΗ 1' },
    { value: '2', label: 'ΦΑΡΜ. ΑΓΩΓΗ 2' },
    { value: '3', label: 'ΦΑΡΜ. ΑΓΩΓΗ 3' },
    { value: '4', label: 'ΦΑΡΜ. ΑΓΩΓΗ 4' },
    { value: '5', label: 'ΦΑΡΜ. ΑΓΩΓΗ 5' },
    { value: '6', label: 'ΦΑΡΜ. ΑΓΩΓΗ 6' },
    { value: '7', label: 'ΦΑΡΜ. ΑΓΩΓΗ 7' },
    { value: '8', label: 'ΦΑΡΜ. ΑΓΩΓΗ 8' },
    { value: '9', label: 'ΦΑΡΜ. ΑΓΩΓΗ 9' },
    { value: '10', label: 'ΦΑΡΜ. ΑΓΩΓΗ 10' },
    { value: '11', label: 'ΦΑΡΜ. ΑΓΩΓΗ 11' },
    { value: '12', label: 'ΦΑΡΜ. ΑΓΩΓΗ 12' },
    { value: '13', label: 'ΦΑΡΜ. ΑΓΩΓΗ 13' },
    { value: '14', label: 'ΦΑΡΜ. ΑΓΩΓΗ 14' },
    { value: '15', label: 'ΦΑΡΜ. ΑΓΩΓΗ 15' },
    { value: '16', label: 'ΦΑΡΜ. ΑΓΩΓΗ 16' },
    { value: '17', label: 'ΦΑΡΜ. ΑΓΩΓΗ 17' },
    { value: '18', label: 'ΦΑΡΜ. ΑΓΩΓΗ 18' },
    { value: '19', label: 'ΦΑΡΜ. ΑΓΩΓΗ 19' },
    { value: '20', label: 'ΦΑΡΜ. ΑΓΩΓΗ 20' },
    { value: '21', label: 'ΦΑΡΜ. ΑΓΩΓΗ 21' },
    { value: '22', label: 'ΦΑΡΜ. ΑΓΩΓΗ 22' },
    { value: '23', label: 'ΦΑΡΜ. ΑΓΩΓΗ 23' },
    { value: '24', label: 'ΦΑΡΜ. ΑΓΩΓΗ 24' },
    { value: '25', label: 'ΦΑΡΜ. ΑΓΩΓΗ 25' },
    { value: '26', label: 'ΦΑΡΜ. ΑΓΩΓΗ 26' },
    { value: '27', label: 'ΦΑΡΜ. ΑΓΩΓΗ 27' },
    { value: '28', label: 'ΦΑΡΜ. ΑΓΩΓΗ 28' },
    { value: '29', label: 'ΦΑΡΜ. ΑΓΩΓΗ 29' },
    { value: '30', label: 'ΦΑΡΜ. ΑΓΩΓΗ 30' },
    { value: '31', label: 'ΦΑΡΜ. ΑΓΩΓΗ 31' },
    { value: '32', label: 'ΦΑΡΜ. ΑΓΩΓΗ 32' },
    { value: '33', label: 'ΦΑΡΜ. ΑΓΩΓΗ 33' },
    { value: '34', label: 'ΦΑΡΜ. ΑΓΩΓΗ 34' },
    { value: '35', label: 'ΦΑΡΜ. ΑΓΩΓΗ 35' },
    { value: '36', label: 'ΦΑΡΜ. ΑΓΩΓΗ 36' },
    { value: '37', label: 'ΦΑΡΜ. ΑΓΩΓΗ 37' },
    { value: '38', label: 'ΦΑΡΜ. ΑΓΩΓΗ 38' },
];