export const treatments = [
    { value: '1', label: 'Παρακεταμόλη (Depon, Panadol)' },
    { value: '2', label: 'Ιβουπροφαίνη (Brufen, Nurofen)' },
    { value: '3', label: 'Ναπροξένη (Naprosyn, Synflex)' },
    { value: '4', label: 'Δικλοφαινάκη (Voltaren, Biofenac)' },
    { value: '5', label: 'Ετορικοξίμπη (Arcoxia)' },
    { value: '6', label: 'Μελοξικάμη (Mobic)' },
    { value: '7', label: 'Τιζανιδίνη (Sirdalud)' },
    { value: '8', label: 'Τραμαδόλη (Tramal, Contramal)' },
    { value: '9', label: 'Θειϊκή Μορφίνη (MST, Dolcontin)' },
    { value: '10', label: 'Καπσαϊκίνη (Capsicum gel)' },
    { value: '11', label: 'Φυσικοθεραπεία – Ενδυνάμωση' },
    { value: '12', label: 'Κρυοθεραπεία (παγοθεραπεία)' },
    { value: '13', label: 'Θερμοθεραπεία (θερμά επιθέματα)' },
    { value: '14', label: 'Ηλεκτροθεραπεία (TENS)' },
    { value: '15', label: 'Manual Therapy (Χειρομαλάξεις)' },
    { value: '16', label: 'Υδροθεραπεία' },
    { value: '17', label: 'Κινησιοθεραπεία' },
    { value: '18', label: 'Εκπαίδευση στάσης σώματος' },
    { value: '19', label: 'Ορθωτικά βοηθήματα' },
    { value: '20', label: 'Αναλγητικά επιθέματα/gel' },
];